import Head from "next/head";
import Image from "next/image";
import { BeakerIcon, PhoneIcon } from "@heroicons/react/solid";

export default function Home() {
  return (
    <div className="text-gray-700">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col h-[100vh] container mx-auto border max-w-screen-2xl   rounded lg:grid lg:grid-cols-4 xl:grid-cols-5 ">
        {/* Header */}
        <div className="flex items-center justify-between gap-2 py-2 px-4 shadow  lg:flex-col lg:items-stretch lg:justify-start lg:gap-2 lg:m-0 lg:p-0 bg-gray-100">
          <h1 className="text-2xl font-bold text-green-500 lg:text-center lg:border-b lg:py-6">
            Logo
          </h1>
          <button className="text-gray-700 font-bold  py-2 px-4 rounded cursor-pointer hover:bg-gray-100 active:scale-90 lg:py-6 ">
            Inbox
          </button>
          <button className="text-gray-700 font-bold  py-2 px-4 rounded cursor-pointer hover:bg-gray-100 active:scale-90 lg:py-6">
            All
          </button>
          <button className="text-gray-700 font-bold  py-2 px-4 rounded cursor-pointer hover:bg-gray-100 active:scale-90 lg:py-6">
            Archived
          </button>
        </div>

        {/* Main */}

        <div className="flex flex-col gap-8 mt-4 max-h-[85vh] lg:max-h-[100vh] overflow-y-auto col-span-3 row-span-2">
          <h2 className="hidden lg:block text-center text-xl font-bold m-0 p-0">
            Calls List
          </h2>

          {Array(10)
            .fill(1)
            .map((item, index) => (
              <div
                key={index}
                className="grid grid-cols-5 sm:grid-cols-7 content-center place-content-center gap-x-2 gap-y-2  py-2 px-4 border mx-4 rounded-md text-gray-700"
              >
                <div className="">
                  <PhoneIcon className="h-5 w-5 inline" />
                  <span className="text-xs font-bold text-gray-400 hidden sm:inline ml-2">
                    300s
                  </span>
                </div>

                <p className=""> From:</p>
                <p className=" font-bold col-span-2"> James Bond</p>
                <p className="  text-sm flex items-center justify-end ">
                  20 July
                </p>
                <div className="hidden sm:flex sm:col-span-2 text-sm font-bold items-center justify-end">
                  <button className=" px-4 py-1 border rounded hover:bg-gray-100 active:scale-90">
                    Archive
                  </button>
                </div>

                <p className="  text-sm flex items-center  ">Missed</p>
                <p className="">To: </p>
                <p className=" font-bold col-span-2">Scrooge McDuck</p>
                <p className=" text-right text-sm flex items-center justify-end ">
                  10:52 PM
                </p>
                <p className="hidden sm:inline-flex sm:col-span-2 text-sm font-bold items-center justify-end">
                  Via: Call Center
                </p>
              </div>
            ))}
        </div>

        {/* Sidebar- Favories- Visible only on x-large screen */}

        <div className="hidden xl:flex xl:row-span-2 border  flex-col xl:max-h-[100vh] overflow-y-auto text-gray-700">
          <h2 className="text-lg  font-bold border-b p-6 text-center">
            Favorites
          </h2>

          {Array(10)
            .fill(1)
            .map((item, index) => (
              <div
                key={index}
                className="flex items-center justify-between gap-4 border-b rounded px-2 py-4"
              >
                <img
                  src="https://avatars.dicebear.com/api/adventurer/Scrooge%20Mc.svg"
                  alt=""
                  className=" h-10 w-10 rounded-full border "
                />
                <p className="">Tom Cruise</p>
                <button className="text-sm font-bold px-4 py-1 border rounded hover:bg-gray-100 active:scale-90">
                  Call
                </button>
              </div>
            ))}
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-2 py-2 px-4  my-4 shadow lg:flex-col lg:items-stretch lg:justify-start lg:gap-2 lg:m-0 lg:p-0 bg-gray-100 border-t">
          <button className="text-gray-700 font-bold  py-2 px-2 rounded cursor-pointer hover:bg-gray-100 active:scale-90 text-sm lg:py-6">
            Calls
          </button>
          <button className="text-gray-700 font-bold  py-2 px-2 rounded cursor-pointer hover:bg-gray-100 active:scale-90 text-sm  lg:py-6">
            Contacts
          </button>
          <button className="text-gray-700 font-bold  py-2 px-2 rounded cursor-pointer hover:bg-gray-100 active:scale-90 text-sm  lg:py-6">
            Home
          </button>
          <button className="text-gray-700 font-bold  py-2 px-2 rounded cursor-pointer hover:bg-gray-100 active:scale-90 text-sm lg:py-6">
            Settings
          </button>
          <button className="text-gray-700 font-bold  py-2 px-2 rounded cursor-pointer hover:bg-gray-100 active:scale-90 text-sm lg:py-6">
            Favorites
          </button>
        </div>
      </div>
    </div>
  );
}
